### ISSUE TITLE
有时候没有打卡却返回今天已经打卡(hadFill为None)

### ISSUE THREAD

**Issue by slightin** [zimin9/YiFuDaoPuncher#13]
如题，有时候今天没有打卡却返回今天已经打卡
日志如下，其中问卷Id为None，hadFill也为None
```python
[2022-05-05 12:12:56] [INFO] {
    'title': '2022-05-05健康上报', 
    'description': '每日健康情况登记', 
    'hadFinish': None, 
    'questionnairePublishEntityId': None,
    'fillStartTime': 1651744800000, 'curTimeStamp': 1651723974558, 
    'hadFill': None, 
    'hadFillUseCache': True
}
```
有时候手动打开奕辅导会出现没有问题和选项，页面是白板的情况
捕获到问卷id和hadfill为none是不是和这种情况有关

**Comment by zimin9** [comment]
这种问题有可能是服务端的问题，需要一段时间的观察（是不是有规律，还是随机）。questionnairePublishEntityId应该是每一次打卡都会变的，无需操心，如果服务端给了None那谁都打不了卡。

目前我自己的打卡倒是没有任何影响。

**Comment by slightin** [comment]
是随机的，
之前不用脚本手动打卡的时候也是有几率出现没有问题选项，页面是白板的情况，需要退出重进才可以
估计可能是某一时刻点进去的用户过多，服务器处理不了高并发没有生成问卷ID

**Comment by Last-ID** [comment]
假如是这样的话，可以写到cron里，每天0到12点随机间隔一到俩小时尝试打卡一次，然后重复打卡的消息取消推送，

**Comment by Last-ID** [comment]
当然更好的解决方式是判断传回的hadfill参数是啥，假如**不是已填写**的话，隔一段时间再尝试

**Comment by zimin9** [comment]
#14
