### ISSUE TITLE
关于不同问题咋设置

### ISSUE THREAD

**Issue by Avalon913** [zimin9/YiFuDaoPuncher#5]
![屏幕截图 2022-01-04 223533](https://user-images.githubusercontent.com/90371683/148077962-b630763c-b341-4400-8644-da944eb1dc76.png)
![屏幕截图 2022-01-04 223546](https://user-images.githubusercontent.com/90371683/148078007-11eda793-91ce-4d75-9ce6-4049fb4cdd52.png)我想问下这不同问题咋设置,好像跟大佬你的完全不一样

**Comment by baifan97** [comment]
抓包抓到什么就填什么..

**Comment by Last-ID** [comment]
根据此前抓包情况，每天的问题id不会变，具体可以看 #3

**Comment by zimin9** [comment]
你可以看一下issue3里的说明 #3 

后面我尽量把生成打卡数据也写成脚本的一个功能

**Comment by Avalon913** [comment]
谢谢各位大佬,麻烦你们了

**Comment by zimin9** [comment]
#7
