### ISSUE TITLE
添加生成打卡数据的功能

### ISSUE THREAD

**Issue by zimin9** [zimin9/YiFuDaoPuncher#7]
#5

**Comment by Chorer** [comment]
经过测试：

* 当天未打卡的情况下请求问卷内容，返回的 hadFill 字段为 false，answerInfoList 为空
* 当天打卡的情况下请求问卷内容，返回的 hadFill 字段为 true，answerInfoList 为本次打卡提交的打卡数据

所以对于初次使用脚本的用户，只需要让他们手动打卡一次，之后再请求问卷内容，就可以获取 answerInfoList 并缓存下来，以后每次请求就 post 这个 answerInfoList 即可。这样做应该适配各个高校的问卷，而且不用抓包分析。

**Comment by zimin9** [comment]
> 经过测试：
> 
> * 当天未打卡的情况下请求问卷内容，返回的 hadFill 字段为 false，answerInfoList 为空
> * 当天打卡的情况下请求问卷内容，返回的 hadFill 字段为 true，answerInfoList 为本次打卡提交的打卡数据
> 
> 所以对于初次使用脚本的用户，只需要让他们手动打卡一次，之后再请求问卷内容，就可以获取 answerInfoList 并缓存下来，以后每次请求就 post 这个 answerInfoList 即可。这样做应该适配各个高校的问卷，而且不用抓包分析。

好思路！确实方便不少
